#if UNITY_EDITOR

using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

namespace UIStackSystem.Editor
{
    static class UIAnimationCodeGenerator
    {
        // Лучше хранить все генерируемые файлы в одной папке.
        private static string OutputFolder
        {
            get
            {
                // Ищем текущий файл генератора среди ассетов.
                // Это позволяет перемещать UIStackSystem куда угодно в проекте
                // без изменения кода.
                string[] guids = AssetDatabase.FindAssets("UIAnimationCodeGenerator t:Script");

                if (guids.Length == 0)
                    throw new Exception("Cannot find UIAnimationCodeGenerator script path.");

                string scriptPath = AssetDatabase.GUIDToAssetPath(guids[0]);

                string directory = Path.GetDirectoryName(scriptPath);

                string generatedFolder = Path.Combine(directory, "Generated");

                if (!AssetDatabase.IsValidFolder(generatedFolder))
                {
                    AssetDatabase.CreateFolder(directory, "Generated");
                }

                return NormalizePath(generatedFolder);
            }
        }

        private static string NormalizePath(string path)
        {
            return path.Replace("\\", "/");
        }

        public static void Generate()
        {
            Directory.CreateDirectory(OutputFolder);

            Type[] types = TypeCache.GetTypesDerivedFrom<object>().ToArray();

            Type[] openAnimations = types.Where(t => !t.IsAbstract && !t.IsInterface && typeof(IPageOpenAnimation).IsAssignableFrom(t))
                                         .OrderBy(t => t.Name).ToArray();

            Type[] closeAnimations = types.Where(t => !t.IsAbstract && !t.IsInterface && typeof(IPageCloseAnimation).IsAssignableFrom(t))
                                          .OrderBy(t => t.Name).ToArray();

            GenerateEnum("UIPageOpenAnimation", openAnimations);

            GenerateEnum("UIPageCloseAnimation", closeAnimations);

            GenerateFactory(openAnimations, closeAnimations);

            AssetDatabase.Refresh();
        }

        private static void GenerateEnum(string enumName, Type[] animationTypes)
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine();

            sb.AppendLine("namespace UIStackSystem");
            sb.AppendLine("{");

            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");

            foreach (Type type in animationTypes)
            {
                // Используем имя класса напрямую.
                // Это гарантирует однозначное соответствие enum -> класс.
                sb.AppendLine($"        {type.Name},");
            }

            sb.AppendLine("    }");

            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(OutputFolder, enumName + ".cs"), sb.ToString());
        }

        private static void GenerateFactory(Type[] openAnimations, Type[] closeAnimations)
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace UIStackSystem");
            sb.AppendLine("{");
            sb.AppendLine("    public static class UIPageAnimationFactory");
            sb.AppendLine("    {");

            //
            // Open
            //

            sb.AppendLine("        public static IPageOpenAnimation Create(UIPageOpenAnimation animation)");
            sb.AppendLine("        {");
            sb.AppendLine("            return animation switch");
            sb.AppendLine("            {");

            foreach (Type type in openAnimations)
            {
                sb.AppendLine($"                UIPageOpenAnimation.{type.Name} => new {type.FullName}(),");
            }

            sb.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(animation))");
            sb.AppendLine("            };");
            sb.AppendLine("        }");

            sb.AppendLine();

            //
            // Close
            //

            sb.AppendLine("        public static IPageCloseAnimation Create(UIPageCloseAnimation animation)");
            sb.AppendLine("        {");
            sb.AppendLine("            return animation switch");
            sb.AppendLine("            {");

            foreach (Type type in closeAnimations)
            {
                sb.AppendLine($"                UIPageCloseAnimation.{type.Name} => new {type.FullName}(),");
            }

            sb.AppendLine("                _ => throw new ArgumentOutOfRangeException(nameof(animation))");
            sb.AppendLine("            };");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(OutputFolder, "UIPageAnimationFactory.cs"), sb.ToString());
        }
    }
}

#endif
