// <auto-generated/>

using System;

namespace UIStackSystem
{
    public static class UIPageAnimationFactory
    {
        public static IPageOpenAnimation Create(UIPageOpenAnimation animation)
        {
            return animation switch
            {

                _ => throw new ArgumentOutOfRangeException(nameof(animation), animation, null)
            };
        }

        public static IPageCloseAnimation Create(UIPageCloseAnimation animation)
        {
            return animation switch
            {

                _ => throw new ArgumentOutOfRangeException(nameof(animation), animation, null)
            };
        }
    }
}
